### ISSUE TITLE
Could not find parent it/unimi/dsi/fastutil/doubles/AbstractDoubleList

### ISSUE THREAD

**Issue by INFIERNOXIII** [Reforged-Hub/radium-upstream#16]
### Version Information

> - Java Version : graalvm-ee-java17-22.3.4
> - Minecraft Version : 1.20.1
> - Forge version : 47.2.0
> - Radium version : radium-mc1.20.1-0.12.2+git.5f80f74
### Expected Behavior

> No error in log

### Actual Behavior
> An error in server log
```
[11:01:52] [ForkJoinPool.commonPool-worker-2/ERROR] [ne.mi.ev.EventSubclassTransformer/EVENTBUS]: Could not find parent it/unimi/dsi/fastutil/doubles/AbstractDoubleList for class me/jellysquid/mods/lithium/common/shapes/lists/OffsetFractionalDoubleList in classloader jdk.internal.loader.ClassLoaders$AppClassLoader@10f87f48 on thread Thread[ForkJoinPool.commonPool-worker-2,8,SERVER]

[11:01:52] [ForkJoinPool.commonPool-worker-2/ERROR] [ne.mi.ev.EventSubclassTransformer/EVENTBUS]: An error occurred building event handler
java.lang.ClassNotFoundException: it.unimi.dsi.fastutil.doubles.AbstractDoubleList
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
        at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:97) ~[eventbus-6.0.5.jar%2352!/:?] {}
        at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:48) ~[eventbus-6.0.5.jar%2352!/:?] {}
        at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:26) ~[eventbus-6.0.5.jar%2352!/:?] {}
        at net.minecraftforge.eventbus.service.ModLauncherService.processClassWithFlags(ModLauncherService.java:32) ~[eventbus-6.0.5.jar%2352!/:6.0.5+6.0.5+master.eb8e549b] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
        at me.jellysquid.mods.lithium.common.shapes.VoxelShapeAlignedCuboidOffset.m_7700_(VoxelShapeAlignedCuboidOffset.java:137) ~[?:?] {re:classloading}
        at net.minecraft.world.phys.shapes.Shapes.m_83148_(Shapes.java:148) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:lithium.mixins.json:shapes.optimized_matching.VoxelShapesMixin,pl:mixin:APP:lithium.mixins.json:shapes.shape_merging.VoxelShapesMixin,pl:mixin:APP:lithium.mixins.json:shapes.specialized_shapes.VoxelShapesMixin,pl:mixin:APP:mixins.bosses_of_mass_destruction.json:multipart_entities.MixinVoxelShapes,pl:mixin:A}
        at com.simibubi.create.content.contraptions.Contraption.lambda$gatherBBsOffThread$17(Contraption.java:1326) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:computing_frames,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}
```
### Reproduction Steps

> 1 Start the server

> 2 Error in log

### Other Information

> Mods List :
![mods_4](https://github.com/Reforged-Hub/radium-upstream/assets/74121661/70aa6a3f-8f8b-4a77-9185-5f7046dbb74f)
![mods_3](https://github.com/Reforged-Hub/radium-upstream/assets/74121661/6caa513c-f797-46ef-b8fd-32a809ee76e1)
![mods_2](https://github.com/Reforged-Hub/radium-upstream/assets/74121661/0cdfc475-6d8f-4f87-9137-cf3d3fabbb8d)
![mods_1](https://github.com/Reforged-Hub/radium-upstream/assets/74121661/39be9e85-e535-40a9-93af-27d23a4a6089)

**Comment by dima-dencep** [comment]
Try forge 47.1.3
